- name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERIRIFA_SOL }}'  # ‚Üê NUEVO NOMBRE
        channelId: live
        projectId: veririfa-sol-2
        entryPoint: "./"
